language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --prefer-source --dev
  - export PATH=./bin/:$PATH
  - phpenv config-add travis.php.ini

script:
  - ./bin/phing test

after_script:
  - php ./bin/coveralls -v